# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ddf012ab77388e70689e1bad7a10e866efb6b8773343ff41c072143f57654f6db9e24e96e1fb66e249c0fb88c503ab13ef15ffb11edfb41d0c8bcca0f4a1a72

test:
  secret_key_base: 248030074a8e5d94eb4aa8959e98fdf5fda8376fe8441d8a62b007c291683e6f0de856764154f9e8ab5e1f9088bc4ccda9a067e2481b6543d05ea995f198c330

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
